global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # RabbitMQ 内置 Prometheus 插件
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['127.0.0.1:15692']
